### ISSUE TITLE
Solid start!

### ISSUE THREAD

**Issue by alOlsen** [CabieM/HW1#1]
Solid start!

Please refer to the class site for the minimum requirements for this assignment. 

Update and push your update ! Then close this issue

Thanks

**Comment by CabieM** [comment]
Thanks Al.  I'm lost as to how to update this repo.  How do I bring this
repo back into Git to make my updates?

Thanks

**Comment by alOlsen** [comment]
If you don't have the local folder you can recreate one and connect to this repo using the command `git remote add origin "add the url to the git repo here"`. After the remote is added, you can run the command: `git pull origin master` to download the source. 

Once downloaded you can make more changes, add them, commit them and push them.

**Comment by CabieM** [comment]
Hey Al, I think I should be all set with HW1.  Please advise if not. Thanks!
